/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package transcribe;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Map;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

import com.google.inject.Binding;
import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Key;

import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;

// TODO: Get app to read logging.properties file
@Slf4j
public class App {

    @SneakyThrows
    private static CommandLine getParsedArgs(String[] args) {
        Options options = new Options();
        options.addOption(Option.builder("i")
                .argName("inputDir")
                .desc("Directory of files to upload")
                .optionalArg(false)
                .hasArg()
                .build());
        options.addOption(Option.builder("o")
                .argName("outputDir")
                .desc("Directory of files to upload")
                .optionalArg(false)
                .hasArg()
                .build());
        CommandLineParser parser = new DefaultParser();
        return parser.parse(options, args);
    }

    public static void main(String[] args) throws ParseException, URISyntaxException, IOException {
        Injector injector = Guice.createInjector(new AppModule());
        Map<Key<?>, Binding<?>> bindings = injector.getAllBindings();
        for (Map.Entry<Key<?>, Binding<?>> entry : bindings.entrySet()) {
            System.out.println(entry.getKey() + " : " + entry.getValue());
        }
        CommandLine cmd = getParsedArgs(args);
        String inputDir = cmd.getOptionValue("i");
        String outputDir = cmd.getOptionValue("o");
        log.info("Processing with input dir {} and output dir {}", inputDir, outputDir);
        TranscribeProcessor processor = injector.getInstance(TranscribeProcessor.class);
        processor.process(inputDir, outputDir);
        log.info("Processed input dir {} into output dir {}", inputDir, outputDir);
    }
}
